language: node_js
node_js:
 - "stable"

cache:
  directories:
    - "node_modules"

addons:
  apt:
    update: true

services :
  - postgresql

postgres:
  adapter: postgresql
  database: DB_DATABASE
  username: postgres

before_script:
  - psql -c 'create database fastfood;' -U postgres

after_success: npm run coverage
